id: P003055
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:37:24.373591
source_metadata:
  id: bdr:W1KG5945
  title: ཆོས་སྡེ་ཆེན་པོ་བླ་བྲང་བཀྲ་ཤིས་འཁྱིལ་།
  author: ''
  volumes:
    a55d86fadb884413bf59e2d25ee10ac2:
      image_group_id: I1KG5947
      title: ''
      volume_number: 1
      total_pages: 473
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
