id: IFA1E0E30
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:48:18+00:00'
last_modified: '2022-06-07T17:15:14.846303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5945
  title: ཆོས་སྡེ་ཆེན་པོ་བླ་བྲང་བཀྲ་ཤིས་འཁྱིལ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EDEA:
      image_group_id: I1KG5947
      title: ''
      total_pages: 473
      order: 1
      base_file: EDEA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
